# Configuration for YOLOv8 Model and Dataset Paths
# Adjust settings here to define model size, class details, and dataset paths

model_size: nano  # Options: nano, small, medium, large, x-large
num_classes: 1   # Number of classes
class_names: ['Vehicle']  # A list of class names

train: fed_dataset/train/images  # Configure paths (usually not needed to be configured)
val: fed_dataset/valid/images
test: fed_dataset/test/images